## Q1. Write a program to distinguish between Array Indexing and Fancy Indexing.

In [1]:
import numpy as np

# Array Indexing
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])  # Output: 1
print(arr[1:4])  # Output: [2 3 4]

# Fancy Indexing
arr = np.array([1, 2, 3, 4, 5])
print(arr[[0, 2, 4]])  # Output: [1 3 5]


1
[2 3 4]
[1 3 5]


## Q2. Execute the 2D array Slicing.

In [2]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing a 2D array
print("Original array:\n", arr)
print("Sliced array:\n", arr[1:, 1:])


Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sliced array:
 [[5 6]
 [8 9]]


## Q3. Create the 5-Dimensional arrays using ‘ndmin’.

In [3]:
import numpy as np

# Create a 5-dimensional array
arr = np.array([1, 2, 3, 4, 5], ndmin=5)

# Print the array and its shape
print("5-Dimensional array:\n", arr)
print("Shape of the array:", arr.shape)

5-Dimensional array:
 [[[[[1 2 3 4 5]]]]]
Shape of the array: (1, 1, 1, 1, 5)


## Q4. Reshape the array from 1-D to 2-D array.

In [4]:
import numpy as np

# Create a 1-D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to a 2-D array
new_arr = arr.reshape(2, 3)

# Print the original and reshaped arrays
print("Original array:\n", arr)
print("Reshaped array:\n", new_arr)

Original array:
 [1 2 3 4 5 6]
Reshaped array:
 [[1 2 3]
 [4 5 6]]


## Q5. Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().

In [5]:
import numpy as np

# Create two 1-D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stack the arrays horizontally
hstack_arr = np.hstack((arr1, arr2))

# Stack the arrays vertically
vstack_arr = np.vstack((arr1, arr2))

# Stack the arrays depth-wise
dstack_arr = np.dstack((arr1, arr2))

# Print the stacked arrays
print("Horizontally stacked array:\n", hstack_arr)
print("Vertically stacked array:\n", vstack_arr)
print("Depth-wise stacked array:\n", dstack_arr)

Horizontally stacked array:
 [1 2 3 4 5 6]
Vertically stacked array:
 [[1 2 3]
 [4 5 6]]
Depth-wise stacked array:
 [[[1 4]
  [2 5]
  [3 6]]]


## Q6. Perform the searchsort method in Numpy array.

In [6]:
import numpy as np

# Create a sorted 1-D array
arr = np.array([1, 2, 3, 4, 5])

# Find the index where 3 should be inserted to maintain the order
index = np.searchsorted(arr, 3)

# Print the index
print("Index where 3 should be inserted:", index)

Index where 3 should be inserted: 2


## 

## Q7. Create Numpy Structured array using your domain features.

In [ ]:
import numpy as np

# Create a structured data type for a student record
student_dtype = np.dtype([('name', 'U20'), ('age', 'i4'), ('marks', 'f4')])

# Create a structured array of student records
students = np.array([('John', 20, 85.5), ('Jane', 22, 90.0)], dtype=student_dtype)

# Print the structured array
print("Structured array of student records:\n", students)

## Q8. Create Data frame using List and Dictionary.

In [7]:
import pandas as pd

# Create a list of dictionaries
data = [{'name': 'John', 'age': 20, 'marks': 85.5},
        {'name': 'Jane', 'age': 22, 'marks': 90.0}]

# Create a DataFrame from the list of dictionaries
df = pd.DataFrame(data)

# Print the DataFrame
print("DataFrame using list of dictionaries:\n", df)

# Create a list of lists
data = [['John', 20, 85.5], ['Jane', 22, 90.0]]

# Create a DataFrame from the list of lists
df = pd.DataFrame(data, columns=['name', 'age', 'marks'])

# Print the DataFrame
print("DataFrame using list of lists:\n", df)

DataFrame using list of dictionaries:
    name  age  marks
0  John   20   85.5
1  Jane   22   90.0
DataFrame using list of lists:
    name  age  marks
0  John   20   85.5
1  Jane   22   90.0


## Q9. Create Data frame on your Domain area and perform the following operations to find and eliminate the missing data from the dataset.
## • isnull()
## • notnull()
## • dropna()
## • fillna()
## • replace()
## • interpolate()

In [8]:
import pandas as pd
import numpy as np

# Create a DataFrame with missing data
data = {'name': ['John', 'Jane', 'Bob', 'Alice'],
        'age': [20, np.nan, 25, 30],
        'gender': ['M', 'F', np.nan, 'F']}
df = pd.DataFrame(data)

# Find missing data using isnull()
print("Missing data:\n", df.isnull())

# Find non-missing data using notnull()
print("Non-missing data:\n", df.notnull())

# Drop missing data using dropna()
df_dropped = df.dropna()
print("DataFrame after dropping missing data:\n", df_dropped)

# Fill missing data using fillna()
df_filled = df.fillna(0)
print("DataFrame after filling missing data:\n", df_filled)

# Replace missing data using replace()
df_replaced = df.replace(np.nan, 'Unknown')
print("DataFrame after replacing missing data:\n", df_replaced)

# Interpolate missing data using interpolate()
df_interpolated = df.interpolate()
print("DataFrame after interpolating missing data:\n", df_interpolated)

Missing data:
     name    age  gender
0  False  False   False
1  False   True   False
2  False  False    True
3  False  False   False
Non-missing data:
    name    age  gender
0  True   True    True
1  True  False    True
2  True   True   False
3  True   True    True
DataFrame after dropping missing data:
     name   age gender
0   John  20.0      M
3  Alice  30.0      F
DataFrame after filling missing data:
     name   age gender
0   John  20.0      M
1   Jane   0.0      F
2    Bob  25.0      0
3  Alice  30.0      F
DataFrame after replacing missing data:
     name      age   gender
0   John     20.0        M
1   Jane  Unknown        F
2    Bob     25.0  Unknown
3  Alice     30.0        F
DataFrame after interpolating missing data:
     name   age gender
0   John  20.0      M
1   Jane  22.5      F
2    Bob  25.0    NaN
3  Alice  30.0      F


C:\Users\nikhi\AppData\Local\Temp\ipykernel_16200\43550651.py:29: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_interpolated = df.interpolate()


## Q10. Perform the Hierarchical Indexing in the above created dataset.

In [9]:
import pandas as pd

# Create a DataFrame with hierarchical indexing
data = {'name': ['John', 'Jane', 'Bob', 'Alice'],
        'age': [20, 22, 25, 30],
        'gender': ['M', 'F', 'M', 'F']}
df = pd.DataFrame(data, columns=['name', 'age', 'gender'])
df.set_index(['gender', 'name'], inplace=True)

# Print the DataFrame with hierarchical indexing
print("DataFrame with hierarchical indexing:\n", df)

# Access data using hierarchical indexing
print("Accessing data using hierarchical indexing:\n", df.loc[('M', 'John')])

DataFrame with hierarchical indexing:
               age
gender name      
M      John    20
F      Jane    22
M      Bob     25
F      Alice   30
Accessing data using hierarchical indexing:
 age    20
Name: (M, John), dtype: int64
