## Q1. Create two 3×3 matrices using the random function in Numpy and perform the following operations.
## è Product (prod)
## è Multiplication (multiply)
## è Dot Product (dot)



In [1]:
import numpy as np

# Create two 3x3 matrices with random values
matrix1 = np.random.rand(3, 3)
matrix2 = np.random.rand(3, 3)

# Calculate the product of the elements in the matrices
product = np.prod(matrix1)

# Perform matrix multiplication
multiplication = np.matmul(matrix1, matrix2)

# Perform dot product
dot_product = np.dot(matrix1, matrix2)

# Print the matrices and the results of the operations
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Product of elements in Matrix 1:", product)
print("Matrix multiplication:\n", multiplication)
print("Dot product:\n", dot_product)

Matrix 1:
 [[0.6794901  0.5952648  0.15253572]
 [0.33841687 0.76106676 0.01585567]
 [0.9553566  0.19063943 0.30402218]]
Matrix 2:
 [[0.93824152 0.2356648  0.46779725]
 [0.95079483 0.58308898 0.89930218]
 [0.1780007  0.61455957 0.24541753]]
Product of elements in Matrix 1: 1.3951078800478488e-05
Matrix multiplication:
 [[1.23065199 0.60096654 0.89062147]
 [1.04395743 0.53326684 0.84663074]
 [1.13173038 0.52314341 0.69296801]]
Dot product:
 [[1.23065199 0.60096654 0.89062147]
 [1.04395743 0.53326684 0.84663074]
 [1.13173038 0.52314341 0.69296801]]


## Q2. Perform the following set operations using the Numpy functions.
## è Union
## è Intersection
## è Set difference
## è XOR


In [2]:
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

# Perform set operations
union = np.union1d(array1, array2)
intersection = np.intersect1d(array1, array2)
set_difference = np.setdiff1d(array1, array2)
xor = np.setxor1d(array1, array2)

# Print the results
print("Array 1:", array1)
print("Array 2:", array2)
print("Union:", union)
print("Intersection:", intersection)
print("Set difference (Array 1 - Array 2):", set_difference)
print("XOR:", xor)

Array 1: [1 2 3 4 5]
Array 2: [4 5 6 7 8]
Union: [1 2 3 4 5 6 7 8]
Intersection: [4 5]
Set difference (Array 1 - Array 2): [1 2 3]
XOR: [1 2 3 6 7 8]


## Q3. Create a 1D array using Random function and perform the following operations.
## è Cumulative sum
## è Cumulative Product
## è Discrete difference (with n=3)
## è Find the unique elements from the array


In [3]:
import numpy as np

# Create a 1D array with random values
array = np.random.rand(10)

# Calculate the cumulative sum of the elements in the array
cumulative_sum = np.cumsum(array)

# Calculate the cumulative product of the elements in the array
cumulative_product = np.cumprod(array)

# Calculate the discrete difference of the array with n=3
discrete_difference = np.diff(array, n=3)

# Find the unique elements from the array
unique_elements = np.unique(array)

# Print the array and the results of the operations
print("Array:", array)
print("Cumulative sum:", cumulative_sum)
print("Cumulative product:", cumulative_product)
print("Discrete difference (n=3):", discrete_difference)
print("Unique elements:", unique_elements)

Array: [0.16068798 0.24918442 0.95708561 0.46746991 0.70573996 0.0392466
 0.05441742 0.25453429 0.92447761 0.31453973]
Cumulative sum: [0.16068798 0.4098724  1.366958   1.83442791 2.54016788 2.57941448
 2.6338319  2.88836619 3.8128438  4.12738353]
Cumulative product: [1.60687982e-01 4.00409409e-02 3.83226082e-02 1.79146662e-02
 1.26430959e-02 4.96198561e-04 2.70018465e-05 6.87289570e-06
 6.35383820e-06 1.99853457e-06]
Discrete difference (n=3): [-1.81692164  1.92540264 -1.63264917  1.5864276  -0.49671814  0.28488042
 -1.74970767]
Unique elements: [0.0392466  0.05441742 0.16068798 0.24918442 0.25453429 0.31453973
 0.46746991 0.70573996 0.92447761 0.95708561]


## Q4. Create two 1D array and perform the Addition using zip(), add() and user defined function (frompyfunc())


In [4]:
import numpy as np

# Create two 1D arrays with random values
array1 = np.random.rand(5)
array2 = np.random.rand(5)

# Addition using zip()
addition_zip = np.array([a + b for a, b in zip(array1, array2)])

# Addition using add()
addition_add = np.add(array1, array2)

# Addition using frompyfunc()
addition_func = np.frompyfunc(lambda x, y: x + y, 2, 1)
addition_frompyfunc = addition_func(array1, array2)

# Print the arrays and the results of the addition
print("Array 1:", array1)
print("Array 2:", array2)
print("Addition using zip():", addition_zip)
print("Addition using add():", addition_add)
print("Addition using frompyfunc():", addition_frompyfunc)

Array 1: [0.52434304 0.86641577 0.29673847 0.07690308 0.4074448 ]
Array 2: [0.44223281 0.52702292 0.43478993 0.7640057  0.87029838]
Addition using zip(): [0.96657585 1.39343869 0.7315284  0.84090879 1.27774318]
Addition using add(): [0.96657585 1.39343869 0.7315284  0.84090879 1.27774318]
Addition using frompyfunc(): [0.9665758467911624 1.3934386887092947 0.7315283976219759
 0.8409087878029724 1.277743181914929]


## Q5. Find the LCM (Least Common Multiple) and GCD (Greatest Common Divisor) of an array of elements using reduce().


In [5]:
import functools
import math

# Define the array of elements
array = [12, 18, 24, 30]

# Find the LCM using reduce() and math.gcd()
lcm = functools.reduce(lambda x, y: (x * y) // math.gcd(x, y), array)

# Find the GCD using reduce() and math.gcd()
gcd = functools.reduce(math.gcd, array)

# Print the array and the results of the LCM and GCD
print("Array:", array)
print("LCM:", lcm)
print("GCD:", gcd)

Array: [12, 18, 24, 30]
LCM: 360
GCD: 6
